[project]
name = "ai-customer-segmentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "joblib>=1.6.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.54",
    "streamlit>=1.63.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "ruff>=0.16.7",
]
